apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: online-boutique-shipping-service
  title: Online Boutique Shipping Service
  description: Gives shipping cost estimates based on the shopping cart.
  tags:
    - go
  annotations:
    github.com/project-slug: roadie-demo/online-boutique
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:roadie-demo/engineering
  lifecycle: production