apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: online-boutique-recommendation-service
  title: Online Boutique Recommendation Service
  description: Recommends other products based on what's given in the cart.
  tags:
    - python
  annotations:
    github.com/project-slug: roadie-demo/online-boutique
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:roadie-demo/engineering
  lifecycle: production