apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: online-boutique
  title: Online Boutique
  description: A cloud-first microservices demo application.
  links:
    - url: https://roadie.io/blog/backstage-monorepo-guide/
      title: Register a Monorepo Tutorial
spec:
  type: url
  targets:
    - ./src/frontend/component.yaml
    - ./src/adservice/component.yaml
    - ./src/cartservice/component.yaml
    - ./src/checkoutservice/component.yaml
    - ./src/currencyservice/component.yaml
    - ./src/emailservice/component.yaml
    - ./src/paymentservice/component.yaml
    - ./src/productcatalogservice/component.yaml
    - ./src/recommendationservice/component.yaml
    - ./src/shippingservice/component.yaml
    - ./src/shoppingassistantservice/component.yaml

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: online-boutique-redis-cache
  description: The s3 bucket with the sample data in it. Doesn't really exist.
spec:
  type: redis-cache
  owner: group:roadie-demo/engineering
  system: online-boutique-system

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  title: Online Boutique Domain
  name: online-boutique-domain
  description: Sample domain which has stuff for demoing.
spec:
  owner: group:roadie-demo/engineering

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  title: Online Boutique System
  name: online-boutique-system
  description: Sample things which are good for demoing.
spec:
  owner: group:roadie-demo/engineering
  domain: online-boutique-domain
  hasPart:
    - Component:online-boutique-ad-service
    - Component:online-boutique-recommendation-service
    - Component:online-boutique-product-catalog-service
    - Component:online-boutique-cart-service
    - Component:online-boutique-shipping-service
    - Component:online-boutique-currency-service
    - Component:online-boutique-frontend
    - Component:online-boutique-payment-service
    - Component:online-boutique-product-catalog-service
    - Component:online-boutique-shopping-assistant-service
    - Component:online-boutique-checkout-service
    - Component:online-boutique-email-service

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: online-boutique-api
  title: Online Boutique API
  description: Sample things which are good for demoing.
spec:
  type: openapi
  lifecycle: production
  owner: group:roadie-demo/solutions
  apiConsumedBy:
    - online-boutique-frontend
  definition:
    $text: ./docs/petstore.json