apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: online-boutique-product-catalog-service
  title: Online Boutique Product Catalog Service
  description: A cloud-first microservices demo application.
  tags:
    - go
  annotations:
    github.com/project-slug: roadie-demo/online-boutique
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:roadie-demo/engineering
  lifecycle: production