apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: online-boutique-checkout-service
  title: Online Boutique Checkout Service
  description: Retrieves user cart, prepares order and orchestrates the payment, shipping and the email notification.
  tags:
    - go
  annotations:
    github.com/project-slug: roadie-demo/online-boutique
    github.com/project-readme-path: ./src/checkoutservice/README.md
    backstage.io/techdocs-ref: dir:.
    pagerduty.com/schedule-id: PVPDKQT
    newrelic.com/dashboard-guid: 'MzcwMjEwN3xWSVp8REFTSEJPQVJEfGRhOjkwMDk4'
spec:
  type: service
  owner: group:roadie-demo/engineering
  lifecycle: production
  dependsOn:
    - Component:online-boutique-payment-service
    - Component:online-boutique-email-service
    - Component:online-boutique-product-catalog-service
    - Component:online-boutique-cart-service
    - Component:online-boutique-shipping-service
    - Component:online-boutique-currency-service