apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: online-boutique-email-service
  title: Online Boutique Email Service
  description: Sends users an order confirmation email (mock).
  tags:
    - python
  annotations:
    github.com/project-slug: roadie-demo/online-boutique
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:roadie-demo/engineering
  lifecycle: production